Updated version number 2.0.0 -> 2.0.1
facebook/device-year-class pull request #37
Opened 2018-04-13 16:40 UTC by elizahale

Updating version number with addition of year class 2016.

2018-04-13 17:48 UTC, zlern2k commented
Can we go 2.1.0? It's basically a backwards-compatible definition change rather than a bugfix.

2018-04-13 17:50 UTC, zlern2k requested changes
Let's go 2.1.0; it's a small update to the definition, not just a bug fix.

2018-04-14 01:13 UTC, elizahale commented
Requested changes made to version 2.1.0

2018-04-14 01:18 UTC, zlern2k approved these changes

2018-04-14 01:19 UTC, merged